# Generated by Django 3.1 on 2020-09-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalg',
            name='videolink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postcalc',
            name='videolink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='postprec',
            name='videolink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='posttrig',
            name='videolink',
            field=models.CharField(default='', max_length=100),
        ),
    ]
