# Generated by Django 3.1 on 2020-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200923_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='postalg',
            name='clip',
            field=models.FileField(null=True, upload_to='user_videos/'),
        ),
    ]
